# Generated by Django 2.2.3 on 2019-07-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0003_auto_20190724_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoints',
            name='dest_type',
            field=models.CharField(default='destination', max_length=255),
            preserve_default=False,
        ),
    ]
