# Generated by Django 2.2.3 on 2019-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0004_geopoints_dest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='geopoints',
            name='country_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geopoints',
            name='dest_pts',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='geopoints',
            name='origin_pts',
            field=models.FileField(upload_to=''),
        ),
    ]
