# Generated by Django 2.2.3 on 2019-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_graphretrieval_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphretrieval',
            name='filepath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
