# Generated by Django 2.2.3 on 2019-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distances', '0002_auto_20190724_0308'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_pts', models.FileField(null=True, upload_to='')),
                ('dest_pts', models.FileField(null=True, upload_to='')),
                ('roads_graph', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='MyFile',
        ),
    ]
